#create the docker script of mongodb

version: '2'
services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

    #create the docker script of transaction application
  mybank:
    image: mybank
    container_name: mybank
    ports:
        - "8080:8080"
    restart: always
    depends_on:
        - mongodb

